/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package VIEW;

import DAO.ContatoDAO;
import DTO.ContatoDTO;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author logpl
 */
public class frmContatoVIEW extends javax.swing.JFrame {

    /**
     * Creates new form frmContatoVIEW
     */
    public frmContatoVIEW() {
        initComponents();
        listarValoresContato();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        txtTelefone = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        btnCadastrar = new javax.swing.JButton();
        btnDELETA = new javax.swing.JButton();
        btnCarregarCampos = new javax.swing.JButton();
        btnLimpar = new javax.swing.JButton();
        btnAtualizar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabelaContato = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("LISTA TELEÔNICA");
        setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        setFont(new java.awt.Font("Courier New", 0, 10)); // NOI18N
        setForeground(java.awt.Color.darkGray);
        setMinimumSize(new java.awt.Dimension(700, 500));
        getContentPane().setLayout(null);

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("NOME");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(65, 85, 37, 17);

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("EMAIL");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(65, 135, 50, 17);

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("TELEFONE");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(65, 185, 110, 17);

        txtNome.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N
        getContentPane().add(txtNome);
        txtNome.setBounds(65, 107, 254, 23);

        txtEmail.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N
        getContentPane().add(txtEmail);
        txtEmail.setBounds(65, 157, 254, 23);

        txtTelefone.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N
        getContentPane().add(txtTelefone);
        txtTelefone.setBounds(65, 207, 254, 23);

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("CÓDIGO");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(65, 29, 70, 17);

        txtId.setEnabled(false);
        txtId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdActionPerformed(evt);
            }
        });
        getContentPane().add(txtId);
        txtId.setBounds(65, 51, 111, 22);

        btnCadastrar.setText("CADASTRAR");
        btnCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarActionPerformed(evt);
            }
        });
        getContentPane().add(btnCadastrar);
        btnCadastrar.setBounds(210, 260, 110, 23);

        btnDELETA.setText("DELETAR");
        btnDELETA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDELETAActionPerformed(evt);
            }
        });
        getContentPane().add(btnDELETA);
        btnDELETA.setBounds(60, 300, 120, 23);

        btnCarregarCampos.setText("CARREGAR CAMPOS");
        btnCarregarCampos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCarregarCamposActionPerformed(evt);
            }
        });
        getContentPane().add(btnCarregarCampos);
        btnCarregarCampos.setBounds(60, 340, 260, 23);

        btnLimpar.setText("LIMPAR");
        btnLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparActionPerformed(evt);
            }
        });
        getContentPane().add(btnLimpar);
        btnLimpar.setBounds(60, 260, 120, 23);

        btnAtualizar.setText("ATUALIZAR");
        btnAtualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtualizarActionPerformed(evt);
            }
        });
        getContentPane().add(btnAtualizar);
        btnAtualizar.setBounds(210, 300, 110, 23);

        tabelaContato.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        tabelaContato.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "CÓDIGO","NOME", "EMAIL", "TELEFONE"
            }
        ));
        jScrollPane2.setViewportView(tabelaContato);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(370, 50, 290, 320);

        jPanel1.setBackground(new java.awt.Color(90, 90, 90));
        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 690, 530);

        setSize(new java.awt.Dimension(700, 450));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdActionPerformed

    private void btnCarregarCamposActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCarregarCamposActionPerformed
        CarregarCampos();
    }//GEN-LAST:event_btnCarregarCamposActionPerformed

    private void btnDELETAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDELETAActionPerformed
        DeletarContatos();
        LimparCampos();
    }//GEN-LAST:event_btnDELETAActionPerformed

    private void btnAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtualizarActionPerformed
        AtualizarContatos();
        LimparCampos();
    }//GEN-LAST:event_btnAtualizarActionPerformed

    private void btnLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparActionPerformed
        LimparCampos();
    }//GEN-LAST:event_btnLimparActionPerformed

    private void btnCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarActionPerformed
        CadastrarContatos();
        LimparCampos();
    }//GEN-LAST:event_btnCadastrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmContatoVIEW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmContatoVIEW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmContatoVIEW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmContatoVIEW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmContatoVIEW().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAtualizar;
    private javax.swing.JButton btnCadastrar;
    private javax.swing.JButton btnCarregarCampos;
    private javax.swing.JButton btnDELETA;
    private javax.swing.JButton btnLimpar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable tabelaContato;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtTelefone;
    // End of variables declaration//GEN-END:variables

    private void listarValoresContato(){
        try {
            ContatoDAO objcontatodao = new ContatoDAO();
            
            DefaultTableModel model = (DefaultTableModel) tabelaContato.getModel();
            
            model.setNumRows(0);
            
            ArrayList<ContatoDTO> lista = objcontatodao.PesquisarContato();
            
            for(int i=0;i < lista.size();i++){
                model.addRow(new Object[]{
                lista.get(i).getId(),
                lista.get(i).getNome(),
                lista.get(i).getEmail(),
                lista.get(i).getTelefone()
            });
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,"frmContatoListarValores"+ e);
        }
    }
    
    
    
    private void CarregarCampos(){
        int setar = tabelaContato.getSelectedRow();
        
        txtId.setText(tabelaContato.getModel().getValueAt(setar, 0).toString());
        txtNome.setText(tabelaContato.getModel().getValueAt(setar, 1).toString());
        txtEmail.setText(tabelaContato.getModel().getValueAt(setar, 2).toString());
        txtTelefone.setText(tabelaContato.getModel().getValueAt(setar, 3).toString());
    }
    
    private void CadastrarContatos(){
        String nome,telefone,email;
        
        nome = txtNome.getText();
        telefone = txtTelefone.getText();
        email = txtEmail.getText();
        
        ContatoDTO objcontatodto = new ContatoDTO();
        objcontatodto.setNome(nome);
        objcontatodto.setEmail(email);
        objcontatodto.setTelefone(telefone);
        
        ContatoDAO objcontatodao = new ContatoDAO();
        objcontatodao.cadastrarContato(objcontatodto);
        
        listarValoresContato();
            
    }
    
    public void AtualizarContatos(){
        String nome,email,telefone;
        int id;
        
        nome = txtNome.getText();
        telefone = txtTelefone.getText();
        email = txtEmail.getText(); 
        id = Integer.parseInt(txtId.getText());
        
            ContatoDTO objcontatodto = new ContatoDTO();
            objcontatodto.setNome(nome);
            objcontatodto.setEmail(email);
            objcontatodto.setTelefone(telefone);
            objcontatodto.setId(id);
        
            ContatoDAO objcontatodao = new ContatoDAO();
            objcontatodao.EditarContato(objcontatodto);
        
            listarValoresContato();
       
    }
    
    public void DeletarContatos(){
        int id;
                
                id = Integer.parseInt(txtId.getText());
                
                ContatoDTO objcontatodto = new ContatoDTO();
                objcontatodto.setId(id);
                
                ContatoDAO objcontatodao = new ContatoDAO();
                objcontatodao.DeletarContato(objcontatodto);
                
                listarValoresContato();
    }
    
    public void LimparCampos(){
        txtId.setText("");
        txtNome.setText("");
        txtEmail.setText("");
        txtTelefone.setText("");
        txtNome.requestFocus();
    }

}
